# Generated by Django 5.0.7 on 2024-08-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.BigIntegerField(blank=True, null=True)),
                ('course_code', models.TextField(blank=True, null=True)),
                ('course_workflow_state', models.TextField(blank=True, null=True)),
                ('topic_id', models.FloatField(blank=True, null=True)),
                ('topic_title', models.TextField(blank=True, null=True)),
                ('topic_user_id', models.FloatField(blank=True, null=True)),
                ('topic_workflow_state', models.TextField(blank=True, null=True)),
                ('entry_id', models.FloatField(blank=True, null=True)),
                ('entry_user_id', models.FloatField(blank=True, null=True)),
                ('entry_workflow_state', models.TextField(blank=True, null=True)),
                ('entry_read_user_id', models.FloatField(blank=True, null=True)),
                ('entry_read_workflow_state', models.TextField(blank=True, null=True)),
                ('entry_created_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'read_data',
                'managed': False,
            },
        ),
    ]
